add test results

diff --git a/.github/workflows/ciTest.yml b/.github/workflows/ciTest.yml
--- a/.github/workflows/ciTest.yml
+++ b/.github/workflows/ciTest.yml
@@ -31,3 +31,8 @@ jobs:
       run: ./gradlew build
     - name: Run tests
       run: ./gradlew test
+    - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: build/reports/tests/test/index.html
