edit test results v13

diff --git a/.github/workflows/ciTest.yml b/.github/workflows/ciTest.yml
--- a/.github/workflows/ciTest.yml
+++ b/.github/workflows/ciTest.yml
@@ -31,20 +31,29 @@ jobs:
       run: ./gradlew build
     - name: Run tests
       run: ./gradlew test
-    - name: Test reports
-      if: success() || failure()
-      uses: actions/upload-artifact@v2
-      with:
-        name: artifact-test
-        path: build/reports/tests/test/index.html
-
-    - name: Use token
-      uses: actions/labeler@v2
-      with:
-        repo-token: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v2
       if: always()
+      uses: actions/upload-artifact@v2-preview
       with:
-        report_paths: '**/build/test-results/test/TEST-*.xml'
+        name: 'test-report'
+        path: build/reports/tests/test/*
+
+
+#    - name: Test reports
+#      if: success() || failure()
+#      uses: actions/upload-artifact@v2
+#      with:
+#        name: artifact-test
+#        path: build/reports/tests/test/index.html
+#
+#    - name: Use token
+#      uses: actions/labeler@v2
+#      with:
+#        repo-token: ${{ secrets.GITHUB_TOKEN }}
+#
+#    - name: Publish Test Report
+#      uses: mikepenz/action-junit-report@v2
+#      if: always()
+#      with:
+#        report_paths: '**/build/test-results/test/TEST-*.xml'
